"""changed embedding type to float[]

Revision ID: 8e6f495a0748
Revises: f3097ba18674
Create Date: 2023-11-09 21:51:47.193643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e6f495a0748'
down_revision = 'f3097ba18674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_visitors', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.ARRAY(sa.Float()),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_visitors', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=sa.ARRAY(sa.Float()),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=False)

    # ### end Alembic commands ###
